apiVersion: apps/v1
kind: Deployment
metadata:
  name: platforms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platformsservice
  template:
    metadata:
      labels: 
        app: platformsservice
    spec:
      containers:
        - name: platformsservice
          image: platformsservice
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: platforms-ip
spec:
  type: ClusterIP
  selector:
    app: platformsservice
  ports:
    - name: platformsservice
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: platforms-np
spec:
  type: NodePort
  selector:
    app: platformsservice
  ports:
    - name: platformsservice
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: platforms-mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2017-latest
          ports:
            - containerPort: 1433
          env:
          - name: MSSQL_PID
            value: "Express"
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mssql
                key: SA_PASSWORD
          volumeMounts:
            - mountPath: /var/opt/mssql/data
              name: mssqldb
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-claim
---
apiVersion: v1
kind: Service
metadata:
  name: platforms-mssql-ip
spec:
  type: ClusterIP
  selector:
    app: mssql
  ports:
    - name: mssql
      protocol: TCP
      port: 1433
      targetPort: 1433        
---
apiVersion: v1
kind: Service
metadata:
  name: platforms-mssql-lb
spec:
  type: LoadBalancer
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433   